"""Configuration constants for DeiT-Base Distilled model."""

DEIT_MODEL_NAME = "deit_base_distilled_patch16_224"
DEIT_PRETRAINED = True
DEIT_IMAGE_SIZE = (224, 224)
DEIT_BATCH_SIZE = 16
DEIT_EPOCHS = 40
DEIT_PATIENCE = 10
DEIT_SEED = 42
DEIT_PHASE1_EPOCHS = 4
DEIT_PHASE1_LR = 1e-3
DEIT_PHASE2_LR_BACKBONE = 5e-6
DEIT_PHASE2_LR_HEAD = 5e-5
DEIT_UNFREEZE_BLOCKS = 12
DEIT_DROPOUT = 0.5
DEIT_WEIGHT_DECAY = 1e-2
DEIT_IN_FEATURES = 768
DEIT_DROP_PATH_RATE = 0.1
DEIT_ACCUMULATION_STEPS = 1
