"""Configuration constants for DeiT-Small Distilled model."""

DEIT_MODEL_NAME = "deit_small_distilled_patch16_224"
DEIT_PRETRAINED = True
DEIT_IMAGE_SIZE = (224, 224)
DEIT_BATCH_SIZE = 32
DEIT_EPOCHS = 30
DEIT_PATIENCE = 8
DEIT_SEED = 42
DEIT_PHASE1_EPOCHS = 5
DEIT_PHASE1_LR = 5e-4
DEIT_PHASE2_LR_BACKBONE = 2e-6
DEIT_PHASE2_LR_HEAD = 2e-5
DEIT_UNFREEZE_BLOCKS = 8
DEIT_DROPOUT = 0.5
DEIT_WEIGHT_DECAY = 1e-2
DEIT_IN_FEATURES = 384
DEIT_DROP_PATH_RATE = 0.1
DEIT_ACCUMULATION_STEPS = 1
